// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNob1cpXEaabwON1Txy1pn7zkWfvUtbek',
    appId: '1:363962344387:web:34471094087e5685e4d376',
    messagingSenderId: '363962344387',
    projectId: 'swiftpay-6ceca',
    authDomain: 'swiftpay-6ceca.firebaseapp.com',
    storageBucket: 'swiftpay-6ceca.firebasestorage.app',
    measurementId: 'G-8988DS4GF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YBZzogexNkxExgRhgVopyqpRqkcU_Hs',
    appId: '1:363962344387:android:48bc748844fe15bde4d376',
    messagingSenderId: '363962344387',
    projectId: 'swiftpay-6ceca',
    storageBucket: 'swiftpay-6ceca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ExCLhEYFDFB3z9UESKLz76c3CUUxuJU',
    appId: '1:363962344387:ios:f85ed0eacdb93bafe4d376',
    messagingSenderId: '363962344387',
    projectId: 'swiftpay-6ceca',
    storageBucket: 'swiftpay-6ceca.firebasestorage.app',
    iosBundleId: 'com.example.swiftpayClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ExCLhEYFDFB3z9UESKLz76c3CUUxuJU',
    appId: '1:363962344387:ios:f85ed0eacdb93bafe4d376',
    messagingSenderId: '363962344387',
    projectId: 'swiftpay-6ceca',
    storageBucket: 'swiftpay-6ceca.firebasestorage.app',
    iosBundleId: 'com.example.swiftpayClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNob1cpXEaabwON1Txy1pn7zkWfvUtbek',
    appId: '1:363962344387:web:485df30a1e1d3f35e4d376',
    messagingSenderId: '363962344387',
    projectId: 'swiftpay-6ceca',
    authDomain: 'swiftpay-6ceca.firebaseapp.com',
    storageBucket: 'swiftpay-6ceca.firebasestorage.app',
    measurementId: 'G-7225DEEKZ2',
  );
}
